### ISSUE TITLE
Make sure user manually, or library automatically, runs nltk.download('punkt').

### ISSUE THREAD

**Issue by leobeeson** [meghdadFar/wordview#36]
## Situation

* It is necessary to have downloaded nltk's `punkt` in order for `nltk.tokenize` to work at this [entry point](https://github.com/meghdadFar/wordview/blob/main/wordview/mwes/mwe.py#L70).
* If the user has not downloaded nltk's `punkt`, the program will just catch the exception without informing that the nltk `punkt` dependency is missing.

## Objective

Either:

* Include instruction to user/collaborator in readme to run the following before using `wordview`:

    ```python
    import nltk
    nltk.download('punkt')
    ```

* Configure poetry to automatically download nltk `punkt`, if in fact poetry can handle such type of downloads.

**Comment by meghdadFar** [comment]
This is already done in the [pyproject.toml l:31](https://github.com/meghdadFar/wordview/blob/b3161c0d7c2e3f95362aa58e78c7f04398659440/pyproject.toml#L31)
 where [this script for downloading NLTK requirements](https://github.com/meghdadFar/wordview/blob/main/bin/downloads.py) is called by running `poetry install`.

**Comment by meghdadFar** [comment]
This issue is resolved for the contributors by adding the script and including instructions in the CONTRIBuTING guidelines. However, the issue still persists for the user of the package because poetry currently does now provide a solution for running the download script at installation time.
